version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  reviewers:
  - gengjiawen
  versioning-strategy: increase

