# image:
#   file: .gitpod.Dockerfile

tasks:
  - init: docker-compose build
    command: docker-compose up
  - init: npm i -g npm-check-updates

vscode:
  extensions:
    - gengjiawen.vscode-npm-dependency
    - gengjiawen.vscode-postfix-ts
    - gengjiawen.npm-dependency-links
