version: '3'

services:
  postgres:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:5-alpine'
    ports:
      - '6379:6379'

volumes:
  redis:
  postgres:
