version: '3'

services:
  postgres:
    image: 'postgres:10-alpine'
    volumes:
    - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
    - '5432:5432'

  redis:
    image: 'redis:4-alpine'

volumes:
  redis:
  postgres:
