version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
        name: setup yarn
        command: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get update && sudo apt-get install yarn
    - run:
        name: setup nodejs
        command: |
          sudo apt purge nodejs
          curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
          sudo apt install -y nodejs
          node --version
          yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: yarn build
    - run: docker-compose up -d
    - run: yarn test
