version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
        name: setup nodejs
        command: |
          source ~/.bashrc
          nvm install node
          npx envinfo
          npm i -g yarn
          yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run:
        name: build
        command: |
          source ~/.bashrc
          yarn build
    - run: docker-compose up -d
    - run:
        name: test
        command: |
          source ~/.bashrc
          yarn test
