version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
        name: setup Node.js
        command: |
          rm -rf /opt/circleci/.nvm/
          sudo apt-get update
          curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt-get install nodejs -y
          sudo npm i -g n
          sudo n latest
          sudo npm i -g yarn
          npx envinfo
          yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run:
        name: build
        command: |
          yarn build
    - run: docker-compose up -d
    - run:
        name: test
        command: |
          npx envinfo
          yarn test
