version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.1
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
        name: setup Node.js
        command: |
          npx envinfo
          npm i -g pnpm
          pnpm i
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run:
        name: build
        command: |
          yarn build
    - run: docker-compose up -d
    - run:
        name: test
        command: |
          npx envinfo
          yarn test
