version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
        name: setup Node.js
        command: |
          sudo apt-get update && sudo apt-get install npm
          sudo npm i -g n@next
          sudo n latest --insecure
          sudo npm i -g yarn
          npx envinfo
          yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run:
        name: build
        command: |
          yarn build
    - run: docker-compose up -d
    - run:
        name: test
        command: |
          yarn test
